# Generated by Django 3.1 on 2020-10-02 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='TiempoEspera',
            new_name='cooldown',
        ),
    ]
