# Generated by Django 3.1 on 2020-09-01 05:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0002_lienzo_pixel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lienzo',
            old_name='Bloqueado',
            new_name='bloqueado',
        ),
        migrations.RenameField(
            model_name='lienzo',
            old_name='Fechafin',
            new_name='fechafin',
        ),
        migrations.RenameField(
            model_name='lienzo',
            old_name='Fechainicio',
            new_name='fechainicio',
        ),
        migrations.RenameField(
            model_name='lienzo',
            old_name='Guardado',
            new_name='guardado',
        ),
        migrations.AddField(
            model_name='pixel',
            name='coordenadaX',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='pixel',
            name='coordenadaY',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='pixel',
            name='dueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lienzo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='vidas',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
