# Generated by Django 3.1 on 2020-10-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Usuarios', '0003_denuncia_denunciausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='aplicada',
            field=models.BooleanField(default=False),
        ),
    ]
