# Generated by Django 3.1 on 2020-09-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20200901_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lienzo',
        ),
        migrations.DeleteModel(
            name='pixel',
        ),
    ]
