# Generated by Django 3.1 on 2020-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20200903_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('guardado', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
    ]
