# Generated by Django 3.1 on 2020-09-08 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lienzo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
                ('fechafin', models.DateTimeField(default=None, null=True)),
                ('guardado', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadaX', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)])),
                ('coordenadaY', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)])),
                ('Red', models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Green', models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Blue', models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Alpha', models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)])),
                ('vidas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lienzo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.lienzo')),
            ],
        ),
    ]
