# Generated by Django 3.1 on 2020-09-03 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lienzo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('guardado', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('vidas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('coordenadaX', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('coordenadaY', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
