# Generated by Django 3.1 on 2020-09-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lienzo',
            old_name='id',
            new_name='idLienzo',
        ),
        migrations.AddField(
            model_name='lienzo',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='pixel',
            unique_together={('coordenadaX', 'coordenadaY', 'lienzo')},
        ),
    ]
