# Generated by Django 3.1 on 2020-09-06 21:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='lienzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.lienzo'),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]), size=4),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='coordenadaX',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='coordenadaY',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)]),
        ),
    ]
