# Generated by Django 3.1 on 2020-10-02 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('Nombre',), ('Red', 'Green', 'Blue', 'Alpha')},
        ),
    ]
