# Generated by Django 3.1 on 2020-09-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Juego.color'),
        ),
    ]
