# Generated by Django 3.1 on 2020-09-18 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_auto_20200917_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='Alpha',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='Blue',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='Green',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='Red',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
    ]
