# Generated by Django 3.1 on 2020-09-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_pixel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='Alpha',
        ),
        migrations.RemoveField(
            model_name='pixel',
            name='Blue',
        ),
        migrations.RemoveField(
            model_name='pixel',
            name='Green',
        ),
        migrations.RemoveField(
            model_name='pixel',
            name='Red',
        ),
    ]
