# Generated by Django 3.1 on 2020-09-07 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0003_auto_20200906_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='coordenadaX',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='coordenadaY',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(51)]),
        ),
    ]
