# Generated by Django 3.1 on 2020-09-20 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Juego', '0003_auto_20200918_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Red', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Green', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Blue', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)])),
                ('Alpha', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(256)])),
            ],
            options={
                'unique_together': {('Red', 'Green', 'Blue', 'Alpha')},
            },
        ),
        migrations.AddField(
            model_name='lienzo',
            name='tamano_max_X',
            field=models.IntegerField(default=51),
        ),
        migrations.AddField(
            model_name='lienzo',
            name='tamano_max_Y',
            field=models.IntegerField(default=51),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='lienzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.lienzo'),
        ),
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.color')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juego.pixel')),
            ],
        ),
    ]
