# Generated by Django 3.1 on 2020-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0006_color_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
