# Generated by Django 3.1 on 2020-09-07 00:44

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0006_auto_20200906_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]), default=[0, 0, 0, 0], size=4),
        ),
    ]
