# Generated by Django 3.1 on 2020-09-07 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0008_auto_20200906_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='color',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
