# Generated by Django 3.1 on 2020-09-07 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0009_auto_20200906_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixel',
            name='color',
        ),
        migrations.AddField(
            model_name='pixel',
            name='Alpha',
            field=models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AddField(
            model_name='pixel',
            name='Blue',
            field=models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AddField(
            model_name='pixel',
            name='Green',
            field=models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AddField(
            model_name='pixel',
            name='Red',
            field=models.PositiveSmallIntegerField(default=255, validators=[django.core.validators.MaxValueValidator(256)]),
        ),
    ]
