# Generated by Django 3.1 on 2020-09-07 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0010_auto_20200907_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienzo',
            name='fechafin',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lienzo',
            name='fechainicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
