# Generated by Django 3.1 on 2020-09-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
