# Generated by Django 3.1 on 2020-10-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_denuncia_denunciausuario'),
        ('Foro', '0002_auto_20201011_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaPost',
            fields=[
                ('denuncia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuarios.denuncia')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foro.post')),
            ],
            bases=('Usuarios.denuncia',),
        ),
        migrations.CreateModel(
            name='DenunciaComment',
            fields=[
                ('denuncia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Usuarios.denuncia')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foro.comment')),
            ],
            bases=('Usuarios.denuncia',),
        ),
    ]
