# Generated by Django 3.1 on 2020-10-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Foro', '0004_auto_20201015_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
