# Generated by Django 3.1 on 2020-10-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0005_auto_20201015_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
